export type Page =
  | 'dashboard'
  | 'comptes'
  | 'portefeuille'
  | 'positions'
  | 'transactions'
  | 'performance'
  | 'statistiques'
  | 'rapports'
  | 'assistant'
  | 'strategies'
  | 'backtesting'
  | 'scanner'
  | 'conseils'
  | 'journal'
  | 'billing'
  | 'alerts'
